---
title: "Formulas Básicas"
author: "Eric Gorgens"
date: "February 10, 2018"
output: html_document
---

## Fórmulas auxiliares de economia


Conjunto de fórmulas necessárias para avaliação econômica de projeto.

### Valor presente

```{r valorPresente}

vp = function(vn, i, n){
  return(vn / (1 + i)^n)
}
    
```


Sequencia de teste para fórmula do valor presente:

```{r vp_teste}
vp(100, 0.10, 0)
vp(100, 0.10, 1)
vp(100, 0.10, 2)
vp(100, 0.10, 3)
```

### Valor futuro

```{r valorFuturo}

vf = function(v, i, n){
  return(v * (1 + i)^n)
}
    
```

Sequencia de teste para fórmula do valor futuro:

```{r vf_teste}
vf(100, 0.10, 0)
vf(100, 0.10, 1)
vf(100, 0.10, 2)
vf(100, 0.10, 3)
```

### Série Finita

```{r seriefinita}

serieFinita = function(a, i, n, presente = TRUE, t = NULL){
    if (presente == TRUE){        
        if (is.null(t)){
            return((a*((1+i)^n)-1)/(i*(1+i)^n))
        }else{
            return((a*((1+i)^(n*t)-1))/(((1+i)^t - 1)*(1+i)^(n*t)))
        }
    }else{
        if(t == None){
            return((a*((1+i)^n - 1))/(i))
        }else{
            return(a*(((1+i)^n*t - 1)/((1+i)^t -1)))
        }
    }
}

```

Testar série finita

```{r sf_teste}
serieFinita(100, 0.10, 12)
```

### Série Infinita

```{r serieinfinita}

serieInfinita = function(a, i, t = NULL){
    if(is.null(t)){
        return(a/i)
    }else{
        return(a/((1+i)^t -1))
    }
}

```

Testar série infinita

```{r si_teste}
serieInfinita(800, 0.01)
```
